### ISSUE TITLE
Compatibility with v10 ?

### ISSUE THREAD

**Issue by R0TEAM** [Tronikart/proper-pixels#2]
will it get an update ?

**Comment by Tronikart** [comment]
Hi! Sorry, haven't had the time to update to v10 myself, but let me get some time and see how much it has changed, it's planned since I have to eventually update but haven't to give some systems (specially the sandbox one) and modules the chance to update themselves first

**Comment by Tronikart** [comment]
Good news! Finally got the time and space to update this
