### ISSUE TITLE
Configuration if affecting tiles and/or tokens

### ISSUE THREAD

**Issue by FPTheFluffyPawed** [Tronikart/proper-pixels#3]
I hope it's not too much to ask, but I'm wondering if there was ever gonna be a status on that configuration? I'm in the situation where my tokens are pixelated but my backgrounds are full-res art, and this module is a savior if it weren't for the odd effect it applies on my tiles.

**Comment by Tronikart** [comment]
So sorry I'm reading this this late! I'll try and get some time to look into configurations, haven't had a lot of free time as of late :( I'll give it a look though!

**Comment by Tronikart** [comment]
This functionality has been added in v1.2.0 in commit e9dfc86aca01bdc77ce2fd2c476f6bfefd6e392f, it's already published to Foundry!
