### ISSUE TITLE
Module doesn't work for backgrounds

### ISSUE THREAD

**Issue by AmoraChinchilla** [Tronikart/proper-pixels#4]
I want to preface this by saying that I love this module and it's been a lifesaver for trying to do a pixel art campaign. My issue is that backgrounds for scenes still look blurry-- which of course the module doesn't claim to fix, so I'm not sure if this actually belongs here, per se.

Is there any plan to extend this to scene backgrounds? And even if not, thank you so much for the work you've done, because this has made things so much nicer!

**Comment by Tronikart** [comment]
Hi! Thank you! Glad this is being useful for others, I currently don't remember the exact reason why, but back then I didn't go for backgrounds, I currently can't really sit to review code and documentation, so what I've been doing is setting a tile with the background and locking it, its certainly not THE solution, but A solution, might be a bit annoying to handle other tiles, I'd recommend the Tile Sort module to aid you if this is the case, hopefully I can get some free time in the future to work on this option as well!

I'll be closing this issue for now, when the backgrounds are taken into account, I'll be sure to mention it!
