### ISSUE TITLE
Not able to update/download module for Version 12

### ISSUE THREAD

**Issue by Luctlapt** [Tronikart/proper-pixels#7]
Whenever trying to update or even download the module for version 12, Foundry gives an error about the module.zip not being found
Error: An unexpected error has occured when downloading file https://github.com/Tronikart/proper-pixels/releases/latest/download/module.zip: Not Found
Thus preventing a download/update

**Comment by Tronikart** [comment]
Heck, I was called into a meeting as I was publishing and forgot to run a simple check, it should be working now, thank you for letting me know!
